#########################
## Client Information
#########################
client:
  name: <%= clientName %>
  homepage: <%= clientHomepage %>

#########################
## Author Information
#########################
author:
  name: <%= authorName %>
  email: <%= authorEmail %>

#########################
## Style Prototype Settings
#########################

## General Prototype Settings
prototype:
  # If you would like a logo to appear in the banner, include its path here
  logo: false
  # If you would like to include webfonts, the following two provides have native support
  webfonts:
    # Typekit Kit ID (uses advanced loading method)
    typekit: false
    # Copy in the the families from inside the brackets [] from the JavaScript tab. Be sure to wrap it in "double quotes". e.g.: "'Open+Sans::latin'"
    googleFonts: false

## Main Navigation Sections
sections:
  Content Strategy: content
  Style Tile: style-tile
  Elements: elements
  Components: components
  Colors: colors

## Style Tile Options
styleTile:
  # Number of possible colors
  colors: 5
  # Source links to inspirational images
  # Either relative paths from your images directory, or absolute paths to external images
  images:
    - patterns/moon.jpg
    - patterns/ice.jpg
    - patterns/iceberg.jpg
    - patterns/clouds.jpg
    - http://lorempixel.com/output/abstract-q-c-640-480-1.jpg
  # Descriptive keywords for Style Tile
  keywords:
    - Default
    - Minimal
    - Nothing
    - Design me!

#########################
## Component Guide
#########################
components:
  message:
    - status
    - warning
    - error
  button:
    - Call to Action:
        classes:
          - call-to-action
    - Big Button:
        classes:
          - big-button
    - Warning Button:
        classes:
          - big-button
          - warning

#########################
## Color Guide
#########################
colors:
  # Variable names of the color variables being used
  variables:
    - black-tints
    - primary-tints
    - primary-shades
    - secondary-tints
    - secondary-shades
    - tertiary-tints
    - tertiary-shades
    - quaternary-tints
    - quaternary-shades
  # The number of shades each color has
  shades: 6

#########################
## Server Options
#########################
server:
  port: 8000
  # If remoteAccess is set to true, you will be able to access your prototype from any device connected to the same network as well as be able to remotely debug them.
  remoteAccess: false

#########################
## Export Options
#########################
export:
  path: export
  # If deploying somewhere (like GitHub Pages) where your files will not be located at the root directory, this will be the prefix that gets appended to assets run through image-url, style-url, script-url, and component-url. If they will be deployed to the root directory, set assetPrefix to ''
  assetPrefix: page

#########################
## Compass Options
#########################
compass:
  debugInfo: false
  # Your dependencies should all go here. Style Prototypes will automatically generate your Bundler Gemfile and Gemfile.lock for you. If you run into dependency issues with Bundler, update your gem versions here.
  dependencies:
    sass: ">=3.2.0"
    compass: '>=0.12.1'
    style-prototypes: "~>1.3.0"

#########################
## Versioning
#########################
bump:
  # Commit your files to Git after your bump
  commit: false
  # What files to commit. -a for all files
  files:
    - -a
  # Create a Git tag after your bump
  tag: false
  # Push changes to Git upstream after your bump
  push: false

#########################
## Git Options
#########################
git:
  # If you use grunt build --commit, this will be git commit message used
  defaultCommit: Production build and commit
  deployUpstream: origin<% if (ghDeploy) { %>
  deployBranch: gh-pages<% } %>
